register:
  hostname: 127.0.0.1
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://${register.hostname}:${register.port}/eureka/
server:
  port: 8764
spring:
  application:
    name: ribbon-user-consumer